name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify your required Python version
 
      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mobile/requirements.txt
          pip install selenium pytest
          pip install chromedriver-autoinstaller
          pip install pytest pytest-bdd

      # Step 4: Run tests
      - name: Run pytest
        id: pytest
        run: |
          pytest -s ./mobile/ -m testhere --template=html1/index.html --report=report/report.html --junitxml=report/junit_report.xml

      # Step 5: Upload test reports as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: report/

  send_email:
    runs-on: ubuntu-latest
    needs: test
    if: always()  # This ensures the job runs regardless of the outcome of the test job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mobile/requirements.txt
          # mkdir -p public
          # mv report/* public/

      - name: Send email
        id: send_email
        run: |
          python ./mobile/send_email.py
