name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2' # Specify your required Python version
 
      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mobile/requirements.txt
          pip install selenium pytest
          pip install chromedriver-autoinstaller
          pip install pytest pytest-bdd

      # Step 4: Run tests
      - name: Run pytest
        id: pytest
        run: |
          pytest -s ./mobile/ -m registration --template=html1/index.html --report=report/report.html --junitxml=report/report.xml
        if: always()
      
      - name: Print report path
        run: |
          ls
        if: always()
      # Step 5: Upload test reports as artifacts
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report/report.html
        if: always()
      # Step 6: Upload screenshots
      - name: Upload screnshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshots
        if: always()

  send_email:
    runs-on: ubuntu-latest
    needs: test
    if: always()  # This ensures the job runs regardless of the outcome of the test job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mobile/requirements.txt
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: report
          path: report
          
      - name: Download screenshot.zip
        uses: actions/download-artifact@v4
        with:
          name: screenshot
          path: screenshot
          
      - name: Send email
        id: send_email
        run: |
          python ./send_email.py
